### ISSUE TITLE
Lifx switch support

### ISSUE THREAD

**Issue by blueatria** [autolog/LIFX_Controller#2]
Any thoughts on support for Lifx switch? Currently discovery sees the switch as an unknown device.

**Comment by autolog** [comment]
This might be a possibility for the future? There is currently no documentation that I can see on the LIFX developer site related to the LIFX Switch. The plugin uses an external LIFX LAN library and that isn't supporting the switch yet. In addition, the LIFX Switch isn't yet available in the UK and so I can't get one to test with - that's assuming I liked the product and wanted to buy one. ;) 

I am in the middle of doing a major code refactoring and enhancement to the LIFX plugin code. The aim being to be able to  manually setup devices without having to do a discovery. The current way of doing things will be maintained by specifying "auto-create" devices but otherwise you can specify the MAC Address and IP address or select from a pull-down of discovered devices to setup a new Indigo device. I am also hoping to ease the "no-ack" problem (we'll see). I will consider how a LIFX Switch might be incorporated into this redesign as I proceed with this change. :)

**Comment by blueatria** [comment]
Sounds good. I have asked Lifx what is happening with HomeKit support and where the api for the switch is, I guess that will be an extension to the  lifxlan protocol. I have not received a response yet. 

Eric

**Comment by autolog** [comment]
I am closing this as I can't get a LIFX Switch in the UK, so can't support it.
I will review this if the situation changes.
